= BP-Base tutorial
:page-pagination:
:description: Learn the fundamentals of Behavioral Programming, and the bp-base language.
:keywords: DSL, basics, BP

In this tutorial we'll learn the _bp-base_ programming/modeling language, and the concepts of Behavioral Programming (which we're going to call _BP_, since it's a lot shorter). The concepts of BP are at the heart of working with the Provengo tools. _bp-base_ is a "low-level" language that is always available for modeling, and is useful for creating models, writing automation handlers, or combining models created in other languages. While it might not be your first modeling language, there's good chance it's going to be your second or third.

Also, it's quite simple and easy to learn, so let's start.

IMPORTANT: bp-base is based on JavaScript, so basic knowledge of core JavaScript is required. This includes values, objects, function calls, loops, and conditionals (``if``/``switch``/``?:``). Knowledge of advanced JavaScript frameworks such as Node.js or React is _not required_.

When completing this tutorial you'll know::
    xyz
This is useful because::
    abc

d;lfjh a;kjsdgb arh g[oauwrbnglsjkn fgkjbsdlkgajb[ uaber libr ]]
