site:
  title: Provengo - Tutorials
  url: https://provengo.github.io/Tutorials/
  keys:
     google_analytics: 'G-RTBT49WYBY'
  start_page: 0.9.5@Tutorials:ROOT:index.adoc
content:
    sources:
    - url: ./../.. # This up-and-down trick is needed to ensure that the root of the Antora project is a git repo.
      start_path: docs/antora/content
      branches: HEAD

asciidoc:
  attributes:
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive (can be overridden by schema with "opts=none")
    kroki-default-options: inline
    icons: font
    page-pagination: true
    experimental: true
    page-toclevels: 4@
  # extensions:
  #  - asciidoctor-kroki
  #  - '@djencks/asciidoctor-mathjax'
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://docs.provengo.tech/ui-bundle/ui-bundle.zip
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
        - index.html
    - path: .nojekyll
    

    
